// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	openProject: (folder: string) => typedError<ProjectInfo, CmdError>(__TAURI_INVOKE("open_project", { folder })),
	/**
	 *  当前项目信息（只读）：前端在 root_file 变化后重新同步用（roadmap P0-②-1）。
	 *  `root_candidates` 不在内存里保存，重新探测以获得与 `open_project` 一致的语义。
	 */
	getProject: () => typedError<ProjectInfo, CmdError>(__TAURI_INVOKE("get_project")),
	listDir: (path: string) => typedError<DirEntryInfo[], CmdError>(__TAURI_INVOKE("list_dir", { path })),
	readFile: (path: string) => typedError<string, CmdError>(__TAURI_INVOKE("read_file", { path })),
	saveAll: (files: FileContent[]) => typedError<null, CmdError>(__TAURI_INVOKE("save_all", { files })),
	/**
	 *  文档大纲（源结构树）：解析在 core `outline` 模块（2026-09-03 从前端下沉）。
	 * 
	 *  输入（roadmap ⑦a 起为增量语义）：
	 *  - `buffers`：**本次新增/变更过**的打开缓冲（未列出的沿用上次上报的内容）——前端只发改动过的，
	 *    避免每次编译成功都把全部打开文件的全文推一遍（实测 462KB 一档 ≈10ms/文件的往返成本）；
	 *  - `open_paths`：当前打开的标签（后端据此淘汰已关闭文件的缓冲；不在此列的缓冲回到读盘）；
	 *  - `files`：无根文件时的兜底文件列表；项目根/根文件取当前项目状态。
	 * 
	 *  未变化的文件由 core 的 `OutlineCache` 按内容指纹复用扫描结果——**每次仍重新取内容**
	 *  （缓冲优先，否则读盘），所以外部改动不会被缓存钉住。
	 */
	getOutline: (buffers: FileContent[], files: string[] | null, openPaths: string[]) => typedError<OutlineNode[], CmdError>(__TAURI_INVOKE("get_outline", { buffers, files, openPaths })),
	compileNow: () => typedError<null, CmdError>(__TAURI_INVOKE("compile_now")),
	abortCompile: () => typedError<null, CmdError>(__TAURI_INVOKE("abort_compile")),
	synctexForward: (file: string, line: number, column: number) => typedError<SyncTexTarget, CmdError>(__TAURI_INVOKE("synctex_forward", { file, line, column })),
	/**
	 *  PDF 点击 → 源码（roadmap ⑤/㉒）：**只回落到项目内真实源码**。
	 * 
	 *  策略本身（就近探测 + 生成产物分类 + 提示文案）在 core [`texpresso_core::synctex::resolve_inverse`]，
	 *  与 headless CLI/MCP 共用一份（roadmap ⑥-P0-3：避免 GUI 与 CLI 行为漂移）；
	 *  这里只做 DTO 映射，并在"完全拿不到映射"时结合文件系统状态补一句更准确的话。
	 */
	synctexInverse: (page: number, x: number | null, y: number | null) => typedError<InverseResultDto, CmdError>(__TAURI_INVOKE("synctex_inverse", { page, x, y })),
	getSettings: () => typedError<Settings, CmdError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  局部更新（modules.md §6）：mode/debounce/timeout/engine → 全局文件；
	 *  root_file → 项目覆盖文件；随后重算有效设置并广播 settings-changed。
	 */
	updateSettings: (patch: SettingsPatch_Deserialize) => typedError<Settings, CmdError>(__TAURI_INVOKE("update_settings", { patch })),
};

/** Events */
export const events = {
	compileStatus: makeEvent<CompileStatusEvent>("compile-status"),
	errorsUpdated: makeEvent<ErrorsUpdatedEvent>("errors-updated"),
	filesChanged: makeEvent<FilesChangedEvent>("files-changed"),
	pdfUpdated: makeEvent<PdfUpdatedEvent>("pdf-updated"),
	settingsChanged: makeEvent<SettingsChangedEvent>("settings-changed"),
};

/* Types */
/**  命令错误契约：{ code, message }（modules.md §4 错误模型）。 */
export type CmdError = { code: "NotFound"; message: string } | { code: "Invalid"; message: string } | { code: "Internal"; message: string };

/**  编译模式（CONTEXT.md：连续编译 / 保存触发编译）。 */
export type CompileMode = "continuous" | "on_save";

/**  编译阶段（modules.md §2.5 事件契约）。 */
export type CompilePhase = "queued" | "running" | "success" | "failed";

/**  编译相关设置。 */
export type CompileSettings = {
	mode: CompileMode,
	debounce_ms: number,
	timeout_secs: number,
	engine: Engine,
};

/**  compile-status 事件载荷。 */
export type CompileStatusDto = {
	phase: CompilePhase,
	kind: FailureKind | null,
	/**
	 *  本次编译是否为**草稿**（`CompileKind::Quick`）——roadmap ㉘。
	 *  前端据此提示"引用待更新"，并在停手后触发一次完整收敛。
	 *  失败/排队阶段同样携带，避免前端在收敛完成前误清提示。
	 */
	draft: boolean,
};

export type CompileStatusEvent = CompileStatusDto;

/**  一条诊断：原因 + 可操作建议。 */
export type Diagnosis = {
	kind: DiagnosisKind,
	/**  人话原因（一句话）。 */
	cause: string,
	/**  怎么改（可操作步骤）。无法给出时为空。 */
	hint: string | null,
	/**
	 *  **一键操作的机器可读参数**（roadmap ㉕）：目前只有超时诊断会给——
	 *  "把 `compile.timeout_secs` 提到这个值再重试一次"。前端据此渲染按钮，
	 *  避免把"该调到多少"这条规则在前后端各写一遍。
	 */
	suggested_timeout_secs: number | null,
	/**
	 *  **缺失的文件名**（roadmap ㉗）：仅"缺文件/缺宏包/缺文档类"三类会给（如 `thuthesis.cls`）。
	 *  调用方据此去项目里找线索（例如同名的 `.ins`/`.dtx` → 源码版模板需先编译生成 `.cls`）。
	 */
	missing_file: string | null,
};

/**  诊断类别（前端据此选图标/分组；测试据此断言）。 */
export type DiagnosisKind = 
/**  缺宏包（`.sty`）。 */
"missing_package" | 
/**  缺文档类（`.cls`）。 */
"missing_class" | 
/**  缺其他文件（图片、`\input` 的子文件等，无 `.sty`/`.cls` 扩展名）。 */
"missing_file" | 
/**  系统缺字体（fontspec）。 */
"missing_font" | 
/**  ctex 字体集不存在（`fontset=` 取值错）。 */
"missing_fontset" | 
/**  引擎不匹配：文档需要 XeLaTeX/LuaLaTeX，当前跑的是 pdfLaTeX（或反之）。 */
"engine_mismatch" | 
/**  需要本产品不支持的引擎（如日文 pLaTeX/upLaTeX）。 */
"unsupported_engine" | 
/**  未定义控制序列。 */
"undefined_control_sequence" | 
/**  组未闭合（`File ended while scanning use of ...`）。 */
"unclosed_group" | 
/**  数学模式外的 `_`/`^`。 */
"missing_math_mode" | 
/**  多余的 `}`。 */
"extra_brace" | 
/**  缺少 `\begin{document}`。 */
"missing_begin_document" | 
/**  重复上下标。 */
"double_script" | 
/**  表格/对齐环境之外的 `&`。 */
"misplaced_alignment" | 
/**  `Emergency stop`（多为连锁反应）。 */
"emergency_stop" | 
/**  宏包选项冲突。 */
"option_clash" | 
/**  源文件含非法 UTF-8（常见于 GBK 旧文件）。 */
"non_utf8_source" | 
/**  **编译超时但在推进**（日志里有页输出）：文档比上限大，不是卡住（roadmap ㉕）。 */
"compile_timeout" | 
/**  **编译超时且无推进证据**（日志里没有任何页输出）：可能仍在做前置处理，也可能真卡住（roadmap ㉕）。 */
"compile_timeout_stalled" | 
/**  **写不出中间文件**：`\include{子目录/文件}` 需要 `tmp/子目录/` 存在，而它不存在（roadmap ㉖ 的首个实测证据）。 */
"aux_write_failed" | 
/**  其他宏包报错（兜底，至少点出宏包名）。 */
"package_error" | 
/**  其他 LaTeX 报错（兜底）。 */
"latex_error";

/**  文件树条目（list_dir 命令输出）。 */
export type DirEntryInfo = {
	name: string,
	path: string,
	is_dir: boolean,
};

/**  TeX 引擎（默认 xelatex，见 design.md）。 */
export type Engine = "xelatex" | "pdflatex" | "lualatex";

/**  错误列表条目（modules.md §4 契约）。 */
export type ErrorEntry = {
	message: string,
	file: string | null,
	line: number | null,
	kind: ErrorKind,
	/**
	 *  诊断（roadmap ④）：把 `.log` 原始报错翻译成「原因 + 怎么改」。
	 *  `None` = 匹配不到已知模式，前端降级为原文 + 行号（宁可不说，也不瞎说）。
	 */
	diagnosis: Diagnosis | null,
};

/**  错误分类（design.md 失败语义 + IO 兜底）。 */
export type ErrorKind = "content_error" | "timeout" | "aborted" | "io";

export type ErrorsUpdatedEvent = ErrorEntry[];

/**  失败原因（与 design.md 失败语义三路对应；Aborted = 手动终止）。 */
export type FailureKind = "timeout" | "content_error" | "aborted";

/**  文件写入载荷（save_all 命令输入）。 */
export type FileContent = {
	path: string,
	content: string,
};

/**
 *  files-changed 事件载荷。
 *  `structural`：是否为结构变化（增/删/重命名）。内容修改（如自动保存）为 false——
 *  文件树因此可跳过重建（modules.md §12「文件树增量刷新」）。
 */
export type FilesChanged = {
	paths: string[],
	structural: boolean,
};

export type FilesChangedEvent = FilesChanged;

/**
 *  `synctex_inverse` 命令输出（roadmap ⑤/㉒）。
 * 
 *  为什么不是一个裸的 `SourcePositionDto`：反向定位**可能没有可跳转的源码**——
 *  命中生成产物（`tmp/main.toc` 等）、系统宏包（`article.cls`），或尚未产生同步数据。
 *  这些情况既不该静默失败（用户点了没反应），也不该把生成文件当源码打开。
 *  故：`source = None` 时用 `note` 说明原因；`note` 也可在成功时补充"已回落到最近源码行"。
 */
export type InverseResultDto = {
	/**  可跳转的源码位置；`None` = 该处没有可打开的源码。 */
	source: SourcePositionDto | null,
	/**  给用户看的一句话（失败原因 / 回落说明）；`None` = 正常直连，无需提示。 */
	note: string | null,
};

/**
 *  文档大纲节点（get_outline 命令输出；解析逻辑见 [`crate::outline`]，2026-09-03 从
 *  前端 `src/stores/outline.ts` 下沉，语义等价、单测锁定）。
 */
export type OutlineNode = {
	/**  标题（`\section[short]{title}` 取 `{...}` 内内容并 trim）。 */
	title: string,
	/**  结构层级：0=part,1=chapter,2=section,3=subsection,4=subsubsection,5=paragraph,6=subparagraph。 */
	level: number,
	/**  项目内绝对路径（已归一化，与前端存储键一致）。 */
	file: string,
	/**  1-based 行号。 */
	line: number,
	/**  文件基名（界面显示用：`file:line`）。 */
	fileBase: string,
	/**  子节点（按文档顺序）。 */
	children: OutlineNode[],
};

/**  pdf-updated 事件载荷。 */
export type PdfUpdated = {
	path: string,
};

export type PdfUpdatedEvent = PdfUpdated;

/**  打开项目后的项目信息（open_project / get_project 命令输出）。 */
export type ProjectInfo = {
	root: string,
	root_file: string | null,
	/**
	 *  根文件探测得到的候选（升序，项目内绝对路径）。
	 * 
	 *  语义（roadmap P0-②-1）：**仅当未使用手动覆盖时**计算——
	 *  - `Unique(p)` → `[p]`（探测到唯一根文件，`root_file` 即它）；
	 *  - `Multiple(list)` → 全部候选（`root_file` 为 None，**由前端让用户选**）；
	 *  - `None` → 空（`root_file` 为 None，前端退回"列出全部 .tex"）；
	 *  - 手动覆盖生效 → 空（用户已指定，不再探测）。
	 * 
	 *  此前 `Multiple` 的候选列表在命令层被直接丢弃，前端只拿到 `root_file: null`
	 *  且仅有 `console.warn`——表现为「打开项目没反应」。
	 */
	root_candidates: string[],
};

/**  合并后的有效设置（全局 + 项目覆盖）。 */
export type Settings = {
	schema_version: number,
	compile: CompileSettings,
	/**  根文件手动覆盖（探测结果的逃生门，ADR-0009）。 */
	root_file: string | null,
};

export type SettingsChangedEvent = Settings;

/**
 *  设置局部更新（update_settings 命令载荷，modules.md §6）。
 * 
 *  只改 Some 的键；`root_file` 语义：缺键 = 不动，`null` = 清除覆盖，字符串 = 设置覆盖。
 */
export type SettingsPatch = SettingsPatch_Serialize | SettingsPatch_Deserialize;

/**
 *  设置局部更新（update_settings 命令载荷，modules.md §6）。
 * 
 *  只改 Some 的键；`root_file` 语义：缺键 = 不动，`null` = 清除覆盖，字符串 = 设置覆盖。
 */
export type SettingsPatch_Deserialize = {
	mode?: CompileMode | null,
	debounce_ms?: number | null,
	timeout_secs?: number | null,
	engine?: Engine | null,
	root_file?: string | null,
};

/**
 *  设置局部更新（update_settings 命令载荷，modules.md §6）。
 * 
 *  只改 Some 的键；`root_file` 语义：缺键 = 不动，`null` = 清除覆盖，字符串 = 设置覆盖。
 */
export type SettingsPatch_Serialize = {
	mode?: CompileMode | null,
	debounce_ms?: number | null,
	timeout_secs?: number | null,
	engine?: Engine | null,
	root_file?: string | null,
};

/**  SyncTeX 反向定位结果（PDF → 源码）。 */
export type SourcePositionDto = {
	file: string,
	line: number,
	/**  列号；-1 = 未知（synctex 1.21 输出契约）。 */
	column: number,
};

/**  SyncTeX 正向定位结果（源码 → PDF）。 */
export type SyncTexTarget = {
	page: number,
	x: number | null,
	y: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

