// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	openProject: (folder: string) => typedError<ProjectInfo, CmdError>(__TAURI_INVOKE("open_project", { folder })),
	/**
	 *  当前项目信息（只读）：前端在 root_file 变化后重新同步用（roadmap P0-②-1）。
	 *  `root_candidates` 不在内存里保存，重新探测以获得与 `open_project` 一致的语义。
	 */
	getProject: () => typedError<ProjectInfo, CmdError>(__TAURI_INVOKE("get_project")),
	listDir: (path: string) => typedError<DirEntryInfo[], CmdError>(__TAURI_INVOKE("list_dir", { path })),
	readFile: (path: string) => typedError<string, CmdError>(__TAURI_INVOKE("read_file", { path })),
	saveAll: (files: FileContent[]) => typedError<null, CmdError>(__TAURI_INVOKE("save_all", { files })),
	/**
	 *  文档大纲（源结构树）：解析在 core `outline` 模块（2026-09-03 从前端下沉）。
	 * 
	 *  输入（roadmap ⑦a 起为增量语义）：
	 *  - `buffers`：**本次新增/变更过**的打开缓冲（未列出的沿用上次上报的内容）——前端只发改动过的，
	 *    避免每次编译成功都把全部打开文件的全文推一遍（实测 462KB 一档 ≈10ms/文件的往返成本）；
	 *  - `open_paths`：当前打开的标签（后端据此淘汰已关闭文件的缓冲；不在此列的缓冲回到读盘）；
	 *  - `files`：无根文件时的兜底文件列表；项目根/根文件取当前项目状态。
	 * 
	 *  未变化的文件由 core 的 `OutlineCache` 按内容指纹复用扫描结果——**每次仍重新取内容**
	 *  （缓冲优先，否则读盘），所以外部改动不会被缓存钉住。
	 */
	getOutline: (buffers: FileContent[], files: string[] | null, openPaths: string[]) => typedError<OutlineNode[], CmdError>(__TAURI_INVOKE("get_outline", { buffers, files, openPaths })),
	compileNow: () => typedError<null, CmdError>(__TAURI_INVOKE("compile_now")),
	abortCompile: () => typedError<null, CmdError>(__TAURI_INVOKE("abort_compile")),
	synctexForward: (file: string, line: number, column: number) => typedError<SyncTexTarget, CmdError>(__TAURI_INVOKE("synctex_forward", { file, line, column })),
	/**
	 *  PDF 点击 → 源码（roadmap ⑤/㉒）：**只回落到项目内真实源码**。
	 * 
	 *  策略本身（就近探测 + 生成产物分类 + 提示文案）在 core [`latteset_core::synctex::resolve_inverse`]，
	 *  与 headless CLI/MCP 共用一份（roadmap ⑥-P0-3：避免 GUI 与 CLI 行为漂移）；
	 *  这里只做 DTO 映射，并在"完全拿不到映射"时结合文件系统状态补一句更准确的话。
	 */
	synctexInverse: (page: number, x: number | null, y: number | null) => typedError<InverseResultDto, CmdError>(__TAURI_INVOKE("synctex_inverse", { page, x, y })),
	getSettings: () => typedError<Settings, CmdError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  局部更新（modules.md §6）：mode/debounce/timeout/engine → 全局文件；
	 *  root_file → 项目覆盖文件；随后重算有效设置并广播 settings-changed。
	 */
	updateSettings: (patch: SettingsPatch_Deserialize) => typedError<Settings, CmdError>(__TAURI_INVOKE("update_settings", { patch })),
	/**
	 *  本次构建是否编入了 Tectonic **库形态**（`tectonic-lib` 特性）。
	 * 
	 *  设置面据此**禁用**该选项并说明原因，而不是让用户选了之后到编译时才炸 —— 那正是"功能开不出来"
	 *  的另一面。（选了但没编进来时 runner 会显式报错，D1：不静默回退到子进程。）
	 */
	libFormAvailable: () => __TAURI_INVOKE<boolean>("lib_form_available"),
	/**
	 *  当前**实际**会用的引擎形态。
	 * 
	 *  **判定只做一次、就在后端**：这里直接调用 runner 用的那个纯函数
	 *  （[`latteset_core::settings::TectonicSettings::use_library_form`]），所以状态栏不可能与编译实际
	 *  行为不一致。前端**不得**从 `compile.engine` 自己推形态 —— `LATTESET_TECTONIC_LIB` 能压过设置，
	 *  只看设置会报出与实际不符的形态。
	 */
	engineForm: () => typedError<EngineFormDto, CmdError>(__TAURI_INVOKE("engine_form")),
};

/** Events */
export const events = {
	compileErrors: makeEvent<CompileErrorsEvent>("compile-errors"),
	compileProgress: makeEvent<CompileProgressEvent>("compile-progress"),
	compileStatus: makeEvent<CompileStatusEvent>("compile-status"),
	errorsUpdated: makeEvent<ErrorsUpdatedEvent>("errors-updated"),
	filesChanged: makeEvent<FilesChangedEvent>("files-changed"),
	pdfUpdated: makeEvent<PdfUpdatedEvent>("pdf-updated"),
	settingsChanged: makeEvent<SettingsChangedEvent>("settings-changed"),
};

/* Types */
/**  命令错误契约：{ code, message }（modules.md §4 错误模型）。 */
export type CmdError = { code: "NotFound"; message: string } | { code: "Invalid"; message: string } | { code: "Internal"; message: string };

/**
 *  编译**进行中**解析到的致命错误（roadmap「阶段 2 · 流式输出」）。
 * 
 *  与 [`ErrorsUpdatedEvent`] **刻意分成两个事件**：后者是**权威终态**（编译结束的完整清单，
 *  含警告），前者是运行中的中间态（只有致命错误）。真机实测（2026-09，长文档超时用例）到混用的
 *  后果：终态写出「错误行 = 1」之后，列表又变回 30 条实时条目。机制上是收尾期的补发——runner
 *  拿到 outcome 后仍要置 stop 并 join 尾随 `.log` 的任务（有 600ms 上限），那次补读照样发事件；
 *  它一旦晚于终态抵达前端，就把权威列表顶掉了。分开后前端按 `phase` 守卫：只在"排版中"接受
 *  实时错误，终态一到便不再理会。
 */
export type CompileErrorsEvent = ErrorEntry[];

/**  编译模式（CONTEXT.md：连续编译 / 保存触发编译）。 */
export type CompileMode = "continuous" | "on_save";

/**  编译阶段（modules.md §2.5 事件契约）。 */
export type CompilePhase = "queued" | "running" | "success" | "failed";

/**  进度载荷（**非权威**中间态；前端只在"排版中"时展示）。 */
export type CompileProgressDto = {
	/**  引擎已输出的最大页码（`[N]` 标记）。 */
	pages: number,
};

/**
 *  编译**进行中**的进度（roadmap「阶段 2 · 流式输出」）：已排版页数。
 *  只在数值变大时发出；编译终态仍由 `compile-status` 给出。
 */
export type CompileProgressEvent = CompileProgressDto;

/**  编译相关设置。 */
export type CompileSettings = {
	mode: CompileMode,
	debounce_ms: number,
	timeout_secs: number,
	engine: Engine,
};

/**  compile-status 事件载荷。 */
export type CompileStatusDto = {
	phase: CompilePhase,
	kind: FailureKind | null,
	/**
	 *  本次编译是否为**草稿**（`CompileKind::Quick`）——roadmap ㉘。
	 *  前端据此提示"引用待更新"，并在停手后触发一次完整收敛。
	 *  失败/排队阶段同样携带，避免前端在收敛完成前误清提示。
	 */
	draft: boolean,
};

export type CompileStatusEvent = CompileStatusDto;

/**  一条诊断：原因 + 可操作建议。 */
export type Diagnosis = {
	kind: DiagnosisKind,
	/**  人话原因（一句话）。 */
	cause: string,
	/**  怎么改（可操作步骤）。无法给出时为空。 */
	hint: string | null,
	/**
	 *  **一键操作的机器可读参数**（roadmap ㉕）：目前只有超时诊断会给——
	 *  "把 `compile.timeout_secs` 提到这个值再重试一次"。前端据此渲染按钮，
	 *  避免把"该调到多少"这条规则在前后端各写一遍。
	 */
	suggested_timeout_secs: number | null,
	/**
	 *  **缺失的文件名**（roadmap ㉗）：仅"缺文件/缺宏包/缺文档类"三类会给（如 `thuthesis.cls`）。
	 *  调用方据此去项目里找线索（例如同名的 `.ins`/`.dtx` → 源码版模板需先编译生成 `.cls`）。
	 */
	missing_file: string | null,
};

/**  诊断类别（前端据此选图标/分组；测试据此断言）。 */
export type DiagnosisKind = 
/**  缺宏包（`.sty`）。 */
"missing_package" | 
/**  缺文档类（`.cls`）。 */
"missing_class" | 
/**  缺其他文件（图片、`\input` 的子文件等，无 `.sty`/`.cls` 扩展名）。 */
"missing_file" | 
/**  系统缺字体（fontspec）。 */
"missing_font" | 
/**  ctex 字体集不存在（`fontset=` 取值错）。 */
"missing_fontset" | 
/**  引擎不匹配：文档需要 XeLaTeX/LuaLaTeX，当前跑的是 pdfLaTeX（或反之）。 */
"engine_mismatch" | 
/**  需要本产品不支持的引擎（如日文 pLaTeX/upLaTeX）。 */
"unsupported_engine" | 
/**  未定义控制序列。 */
"undefined_control_sequence" | 
/**  组未闭合（`File ended while scanning use of ...`）。 */
"unclosed_group" | 
/**  数学模式外的 `_`/`^`。 */
"missing_math_mode" | 
/**  多余的 `}`。 */
"extra_brace" | 
/**  缺少 `\begin{document}`。 */
"missing_begin_document" | 
/**  重复上下标。 */
"double_script" | 
/**  表格/对齐环境之外的 `&`。 */
"misplaced_alignment" | 
/**  `Emergency stop`（多为连锁反应）。 */
"emergency_stop" | 
/**  宏包选项冲突。 */
"option_clash" | 
/**  源文件含非法 UTF-8（常见于 GBK 旧文件）。 */
"non_utf8_source" | 
/**  **编译超时但在推进**（日志里有页输出）：文档比上限大，不是卡住（roadmap ㉕）。 */
"compile_timeout" | 
/**  **编译超时且无推进证据**（日志里没有任何页输出）：可能仍在做前置处理，也可能真卡住（roadmap ㉕）。 */
"compile_timeout_stalled" | 
/**  **写不出中间文件**：`\include{子目录/文件}` 需要 `tmp/子目录/` 存在，而它不存在（roadmap ㉖ 的首个实测证据）。 */
"aux_write_failed" | 
/**  其他宏包报错（兜底，至少点出宏包名）。 */
"package_error" | 
/**  其他 LaTeX 报错（兜底）。 */
"latex_error";

/**  文件树条目（list_dir 命令输出）。 */
export type DirEntryInfo = {
	name: string,
	path: string,
	is_dir: boolean,
};

/**  TeX 引擎（默认 xelatex，见 design.md）。 */
export type Engine = "xelatex" | "pdflatex" | "lualatex" | 
/**
 *  Tectonic（2026-09 引入；方案见 [tectonic-integration-plan.md](../../../docs/research/tectonic-integration-plan.md)）。
 * 
 *  形态 = **子进程驱动官方 `tectonic.exe`**（路线①，`docs/research/tectonic-test-plan.md` §1.2 的 D2 裁决）：
 *  它自带 bundle、**不读用户 TeX Live**，自己出 PDF（`writes_xdv() == false`）⇒ 页级复用 A/B/C
 *  在该引擎下**不可用**（`page_hashes` 恒空 → 前端按"无法判定"保守全量刷新，A 无对应物）。
 */
"tectonic";

/**  引擎形态（库形态方案 §6 P7 的「状态栏可见形态位」）。 */
export type EngineForm = 
/**  子进程档：`latexmk` 驱动 xelatex/lualatex/pdflatex，或直调 `tectonic.exe`。 */
"subprocess" | 
/**  Tectonic **库内嵌**。 */
"lib" | 
/**  形态位要库内嵌，但**本次构建没编入** `tectonic-lib` ⇒ 下一趟编译会显式失败（D1 不静默回退）。 */
"lib_unavailable";

/**  状态栏用的「实际形态」载荷。 */
export type EngineFormDto = {
	form: EngineForm,
	/**  形态位是否由 `LATTESET_TECTONIC_LIB` 强制（**它压过设置**，所以设置面选子进程也可能是库形态）。 */
	env_forced: boolean,
	/**  本次构建是否编入库形态。 */
	lib_compiled_in: boolean,
};

/**  错误列表条目（modules.md §4 契约）。 */
export type ErrorEntry = {
	message: string,
	file: string | null,
	line: number | null,
	kind: ErrorKind,
	/**
	 *  诊断（roadmap ④）：把 `.log` 原始报错翻译成「原因 + 怎么改」。
	 *  `None` = 匹配不到已知模式，前端降级为原文 + 行号（宁可不说，也不瞎说）。
	 */
	diagnosis: Diagnosis | null,
};

/**  错误分类（design.md 失败语义 + IO 兜底）。 */
export type ErrorKind = "content_error" | "timeout" | "aborted" | "io";

export type ErrorsUpdatedEvent = ErrorEntry[];

/**  失败原因（与 design.md 失败语义三路对应；Aborted = 手动终止）。 */
export type FailureKind = "timeout" | "content_error" | "aborted";

/**  文件写入载荷（save_all 命令输入）。 */
export type FileContent = {
	path: string,
	content: string,
};

/**
 *  files-changed 事件载荷。
 *  `structural`：是否为结构变化（增/删/重命名）。内容修改（如自动保存）为 false——
 *  文件树因此可跳过重建（modules.md §12「文件树增量刷新」）。
 */
export type FilesChanged = {
	paths: string[],
	structural: boolean,
};

export type FilesChangedEvent = FilesChanged;

/**
 *  `synctex_inverse` 命令输出（roadmap ⑤/㉒）。
 * 
 *  为什么不是一个裸的 `SourcePositionDto`：反向定位**可能没有可跳转的源码**——
 *  命中生成产物（`tmp/main.toc` 等）、系统宏包（`article.cls`），或尚未产生同步数据。
 *  这些情况既不该静默失败（用户点了没反应），也不该把生成文件当源码打开。
 *  故：`source = None` 时用 `note` 说明原因；`note` 也可在成功时补充"已回落到最近源码行"。
 */
export type InverseResultDto = {
	/**  可跳转的源码位置；`None` = 该处没有可打开的源码。 */
	source: SourcePositionDto | null,
	/**  给用户看的一句话（失败原因 / 回落说明）；`None` = 正常直连，无需提示。 */
	note: string | null,
};

/**
 *  文档大纲节点（get_outline 命令输出；解析逻辑见 [`crate::outline`]，2026-09-03 从
 *  前端 `src/stores/outline.ts` 下沉，语义等价、单测锁定）。
 */
export type OutlineNode = {
	/**  标题（`\section[short]{title}` 取 `{...}` 内内容并 trim）。 */
	title: string,
	/**  结构层级：0=part,1=chapter,2=section,3=subsection,4=subsubsection,5=paragraph,6=subparagraph。 */
	level: number,
	/**  项目内绝对路径（已归一化，与前端存储键一致）。 */
	file: string,
	/**  1-based 行号。 */
	line: number,
	/**  文件基名（界面显示用：`file:line`）。 */
	fileBase: string,
	/**  子节点（按文档顺序）。 */
	children: OutlineNode[],
};

/**
 *  pdf-updated 事件载荷。
 * 
 *  `changed_pages` / `pages`（2026-09，docs/research/incremental-edit-x-dvi.md 的 B/C 两个功能点）：
 *  本次编译相对**上一次**变化的页号（1-based、升序）。前端语义：
 *  - `pages > 0` 且 `changed_pages` **非空** → 只有这些页需要重绘，其余页复用 canvas 位图；
 *  - `pages > 0` 且 `changed_pages` **为空** → 逐页字节完全相同 → **跳过重载**（新旧 PDF 逐页等价，
 *    刷新只会白重绘并可能引起视觉跳动）；
 *  - `pages == 0` → **无法判定**（XDV 缺失/损坏/首次运行拿不到）→ 按全量刷新处理。
 */
export type PdfUpdated = {
	path: string,
	/**  本次变化的页号（1-based）；空表 ≠ "无法判定"——后者看 `pages == 0`。 */
	changed_pages: number[],
	/**  本次编译的页数；`0` 表示页信息不可用。 */
	pages: number,
};

export type PdfUpdatedEvent = PdfUpdated;

/**  打开项目后的项目信息（open_project / get_project 命令输出）。 */
export type ProjectInfo = {
	root: string,
	root_file: string | null,
	/**
	 *  根文件探测得到的候选（升序，项目内绝对路径）。
	 * 
	 *  语义（roadmap P0-②-1）：**仅当未使用手动覆盖时**计算——
	 *  - `Unique(p)` → `[p]`（探测到唯一根文件，`root_file` 即它）；
	 *  - `Multiple(list)` → 全部候选（`root_file` 为 None，**由前端让用户选**）；
	 *  - `None` → 空（`root_file` 为 None，前端退回"列出全部 .tex"）；
	 *  - 手动覆盖生效 → 空（用户已指定，不再探测）。
	 * 
	 *  此前 `Multiple` 的候选列表在命令层被直接丢弃，前端只拿到 `root_file: null`
	 *  且仅有 `console.warn`——表现为「打开项目没反应」。
	 */
	root_candidates: string[],
};

/**  合并后的有效设置（全局 + 项目覆盖）。 */
export type Settings = {
	schema_version: number,
	compile: CompileSettings,
	/**  Tectonic 形态与资源（全局；见 [`TectonicSettings`] 的说明）。 */
	tectonic?: TectonicSettings,
	/**  根文件手动覆盖（探测结果的逃生门，ADR-0009）。 */
	root_file: string | null,
};

export type SettingsChangedEvent = Settings;

/**
 *  设置局部更新（update_settings 命令载荷，modules.md §6）。
 * 
 *  只改 Some 的键；`root_file` 语义：缺键 = 不动，`null` = 清除覆盖，字符串 = 设置覆盖。
 */
export type SettingsPatch = SettingsPatch_Serialize | SettingsPatch_Deserialize;

/**
 *  设置局部更新（update_settings 命令载荷，modules.md §6）。
 * 
 *  只改 Some 的键；`root_file` 语义：缺键 = 不动，`null` = 清除覆盖，字符串 = 设置覆盖。
 */
export type SettingsPatch_Deserialize = {
	mode?: CompileMode | null,
	debounce_ms?: number | null,
	timeout_secs?: number | null,
	engine?: Engine | null,
	root_file?: string | null,
	/**  引擎形态（Tectonic 库内嵌）：`None` = 不动。 */
	lib_form?: boolean | null,
	/**
	 *  bundle 来源：`None` = 不动；**空串 = 清除**（回到上游兜底）；其它 = 设置。
	 * 
	 *  用"空串 = 清除"而不是 `Option<Option<..>>`：设置面总是发具体值，用户清空输入框就是清除，
	 *  语义够用且少一层 `null` 歧义（对比 `root_file` 的历史包袱）。
	 */
	bundle?: string | null,
	/**  缓存目录：同上，**空串 = 清除**（回到宿主应用缓存目录）。 */
	cache_dir?: string | null,
};

/**
 *  设置局部更新（update_settings 命令载荷，modules.md §6）。
 * 
 *  只改 Some 的键；`root_file` 语义：缺键 = 不动，`null` = 清除覆盖，字符串 = 设置覆盖。
 */
export type SettingsPatch_Serialize = {
	mode?: CompileMode | null,
	debounce_ms?: number | null,
	timeout_secs?: number | null,
	engine?: Engine | null,
	root_file?: string | null,
	/**  引擎形态（Tectonic 库内嵌）：`None` = 不动。 */
	lib_form?: boolean | null,
	/**
	 *  bundle 来源：`None` = 不动；**空串 = 清除**（回到上游兜底）；其它 = 设置。
	 * 
	 *  用"空串 = 清除"而不是 `Option<Option<..>>`：设置面总是发具体值，用户清空输入框就是清除，
	 *  语义够用且少一层 `null` 歧义（对比 `root_file` 的历史包袱）。
	 */
	bundle?: string | null,
	/**  缓存目录：同上，**空串 = 清除**（回到宿主应用缓存目录）。 */
	cache_dir?: string | null,
};

/**  SyncTeX 反向定位结果（PDF → 源码）。 */
export type SourcePositionDto = {
	file: string,
	line: number,
	/**  列号；-1 = 未知（synctex 1.21 输出契约）。 */
	column: number,
};

/**  SyncTeX 正向定位结果（源码 → PDF）。 */
export type SyncTexTarget = {
	page: number,
	x: number | null,
	y: number | null,
};

/**
 *  Tectonic 形态与资源设置（⑫ 里程碑的设置面收口项；方案 §3.5）。
 * 
 *  **只在全局设置里**（不进 [`ProjectOverrides`]）：引擎形态由装配点的 runner 决定，而 GUI 侧
 *  的 runner **每趟编译读一次全局设置**（见 `src-tauri` 的 `SwitchableRunner`）；项目级覆盖要走
 *  "形态位随 `CompileRequest` 下发"那条路，属后续项 —— 现在放一个项目级字段只会是**看着能覆盖、
 *  实际不生效**的假开关。
 */
export type TectonicSettings = {
	/**
	 *  引擎形态：`false`（默认）= **子进程**（`tectonic.exe`）；`true` = **库内嵌**（路径 B，ADR-0012）。
	 * 
	 *  需要构建时打开 `tectonic-lib` 特性；没编进去而用户选了库形态时 runner **显式失败**
	 *  （D1：不静默回退到子进程）。
	 */
	lib_form: boolean,
	/**
	 *  bundle 来源：`None`/空 = 上游兜底**网络地址**；否则 `file:///…` 或**相对路径**的目录 bundle。
	 * 
	 *  ⚠ **存储形态**不能是 `E:\…`：上游 `detect_bundle` 会把它当 URL scheme 解析成 `Ok(None)`
	 *  （方案 §5.6 **LB-1**）。入口是宽容的——`E:\…` / `E:/…` / 带引号的「复制为路径」都会被
	 *  [`TectonicSettings::normalize_bundle`] 补成 `file:///…`（`apply_patch` 里归一化在前、
	 *  校验在后），所以 [`super::validate`] 那条只兜底绕过 patch 的写入（手改 `settings.json`）。
	 */
	bundle: string | null,
	/**
	 *  产品缓存目录（`formats/` + `bundles/` 的父目录）：`None`/空 = 宿主的应用缓存目录。
	 * 
	 *  **必须显式给**（或由宿主注入）：上游 format 默认落**项目目录**，不注入就会往用户项目扔
	 *  24 MB 的 `.fmt`（方案 §5.2 硬约束）。
	 */
	cache_dir: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

